Repository tensorflow/ngraph-bridge, pull requests merged in 2019-10, with the labels that each got.

#261 Added IsFiniteOp
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/test_math_ops.cpp
Labels: fully reviewed

#253 Sarkars/fix dump file name and NGraphSerialize/StringToFile now return statuses
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/opexecuter.cpp
  test/python/test_serialize_name.py
Labels: fully reviewed

#256 Shrestha/detect multiple variable updates from the same output of encap
  ngraph_bridge/enable_variable_ops/ngraph_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_catalog.h
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.cc
  test/graph_rewrites/enter_in_catalog_test.cc
  test/graph_rewrites/remove_ngraphassigns.cc
  test/test_utilities.cpp
  test/test_utilities.h
Labels: fully reviewed

#269 shrestha/Added test cases for var as static input
  ngraph_bridge/enable_variable_ops/ngraph_replace_op_utilities.cc
  ngraph_bridge/enable_variable_ops/ngraph_var.h
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  python/ngraph_bridge/__init__.in.py
  test/opexecuter.cpp
  test/python/common.py
  test/python/test_set_backend.py
  test/python/test_variableops_static_input.py
Labels: fully reviewed

#257 Sarkars/some cleanup 1
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_encapsulate_op.h
Labels: Ready to merge

#266 Kanvi/move graph modifications outside loop
  ngraph_bridge/enable_variable_ops/ngraph_remove_ngraphassigns.cc
  ngraph_bridge/enable_variable_ops/ngraph_replace_op_utilities.cc
  ngraph_bridge/ngraph_capture_variables.cc
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_rewrite_for_tracking.cc
Labels: fully reviewed

#279 Kanvi/fix klockwork issue (#265)
  ngraph_bridge/ngraph_rewrite_pass.cc
  test/ci/buildkite/ngtf-cpu_centos.yaml
  test/ci/buildkite/ngtf-cpu_ubuntu-bin-build.yaml
Labels: Ready to merge

#282 Shrestha/detect multiple variable updates merge to master
  ngraph_bridge/enable_variable_ops/ngraph_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_catalog.h
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.cc
  test/graph_rewrites/capture_variables.cc
  test/graph_rewrites/enter_in_catalog_test.cc
  test/graph_rewrites/remove_ngraphassigns.cc
  test/graph_rewrites/test_replace_optimizer.cpp
  test/test_utilities.cpp
  test/test_utilities.h
Labels: Ready to merge

#285 sarkars/Update model testing expected results for nmt
  test/model_level_tests/models/nmt/test1/expected.json
Labels: Ready to merge

#273 Kanvi/Add provenance tag for input/parameter nodes
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_encapsulate_clusters.cc
Labels: fully reviewed

#271 Kanvi/remove files
  diagnostics/README.md
  diagnostics/get_node_encapsulate_map.py
  diagnostics/ngtf_graph_viewer.py
  diagnostics/remove_protobuf_class_attribute.py
  tools/run_tf2ngraph_model.py
Labels: fully reviewed

#291 Vishakha/data cache
  bazel/BUILD
  ngraph_bridge/ngraph_data_cache.h
  test/CMakeLists.txt
  test/test_ngraph_data_cache.cpp
Labels: fully reviewed

#296 sarkars/Fix NgraphSerialize
  ngraph_bridge/ngraph_utils.cc
Labels: Ready to merge, fully reviewed
