Repository tensorflow/ngraph-bridge, pull requests merged in 2019-07, with the labels that each got.

#112 Sindhu/enable multiple batches for cpp examples
  examples/cpp/infer_multiple_networks/inference_engine.cc
  examples/cpp/infer_multiple_networks/inference_engine.h
  examples/cpp/infer_multiple_networks/main.cc
  examples/cpp/infer_single/infer_single.cpp
  examples/cpp/tf_label_image_utils.cc
Labels: fully reviewed, release candidate

#122 Kanvi/config support II
  src/grappler/ngraph_optimizer.cc
  src/ngraph_backend_config.cc
  src/ngraph_backend_config.h
  src/ngraph_backend_manager.cc
  src/ngraph_backend_manager.h
  src/ngraph_encapsulate_op.cc
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/config_for_grappler_test.cc
Labels: fully reviewed, future change

#113 Kanvi/compilation errors
  src/ngraph_api.cc
  src/ngraph_api.h
  src/ngraph_builder.cc
  src/ngraph_encapsulate_clusters.cc
  src/ngraph_encapsulate_op.cc
  src/ngraph_utils.h
  src/tf_deadness_analysis.cc
  test/graph_exec.cpp
  test/graph_rewrites/deadness_test.cc
  test/opexecuter.cpp
  test/test_array_ops.cpp
  test/test_utilities.cpp
  test/tf_exec.cpp
Labels: fully reviewed, release candidate

#125 Kanvi/Move the registrations for ops to a separate location
  bazel/BUILD
  src/CMakeLists.txt
  src/enable_variable_ops/ngraph_assign_op.cc
  src/enable_variable_ops/ngraph_enter_in_catalog.cc
  src/enable_variable_ops/ngraph_tracked_variable.cc
  src/enable_variable_ops/ngraph_variable_modifiers.cc
  src/enable_variable_ops/ops/ngraph_ops.cc
  src/ngraph_encapsulate_op.cc
  src/ngraph_tracked_variable.cc
  src/ops/ngraph_ops.cc
Labels: fully reviewed

#135 Sarkars/Version change preparation
  CMakeLists.txt
  README.md
  bazel/WORKSPACE
  build_ngtf.py
  examples/retrain_ngraph.py
  python/setup.in.py
  src/version.cc
Labels: fully reviewed, release candidate

#141 Kanvi/fix regression some models
  python/ngraph_bridge/__init__.in.py
  src/ngraph_backend_config.cc
  src/ngraph_backend_manager.cc
  test/graph_rewrites/backend_manager_test.cc
Labels: fully reviewed

#110 Shrestha/backend manager fixes
  examples/cpp/infer_multiple_networks/inference_engine.cc
  src/enable_variable_ops/ngraph_rewrite_pass.cc
  src/grappler/ngraph_optimizer.cc
  src/ngraph_api.cc
  src/ngraph_api.h
  src/ngraph_backend_manager.cc
  src/ngraph_backend_manager.h
  src/ngraph_rewrite_pass.cc
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/config_for_grappler_test.cc
  test/python/common.py
  test/python/test_set_backend.py
  test/test_utilities.cpp
  test/test_utilities.h
Labels: Ready to merge, fully reviewed, release candidate

#132 kanvi/implement_encap_output_info_map
  src/enable_variable_ops/ngraph_catalog.cc
  src/enable_variable_ops/ngraph_catalog.h
Labels: Ready to merge, fully reviewed

#145 Sarkars/Version update
  CMakeLists.txt
  README.md
  bazel/WORKSPACE
  build_ngtf.py
  python/setup.in.py
  src/version.cc
Labels: Ready to merge, fully reviewed

#144 Avijit/r16 cherry pick 01
  CMakeLists.txt
  README.md
  bazel/WORKSPACE
  build_ngtf.py
  examples/retrain_ngraph.py
  python/setup.in.py
  src/version.cc
Labels: fully reviewed

#134 Shrestha/remove_ngraphassigns_function
  src/CMakeLists.txt
  src/enable_variable_ops/ngraph_remove_ngraphassigns.cc
  src/enable_variable_ops/ngraph_remove_ngraphassigns.h
  test/CMakeLists.txt
  test/graph_rewrites/remove_ngraphassigns.cc
Labels: Ready to merge, fully reviewed

#130 sarkars/Change inp options
  test/python/test_convert_script.py
  tools/tf2ngraph.py
Labels: Ready to merge, fully reviewed

#136 Kanvi/populate encap output info map
  src/enable_variable_ops/ngraph_catalog.cc
  src/enable_variable_ops/ngraph_catalog.h
  src/enable_variable_ops/ngraph_enter_in_catalog.cc
  src/enable_variable_ops/ngraph_rewrite_pass.cc
  test/CMakeLists.txt
  test/graph_rewrites/enter_in_catalog_test.cc
Labels: Ready to merge, fully reviewed

#151 sarkars/Upgrade ngraph version to 24rc0
  CMakeLists.txt
  bazel/WORKSPACE
  build_ngtf.py
Labels: release candidate

#150 Kanvi/remove additional attr check
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ops/ngraph_ops.cc
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/ngraph_backend_config.cc
  ngraph_bridge/ngraph_backend_config.h
  ngraph_bridge/ngraph_backend_manager.cc
  ngraph_bridge/ngraph_backend_manager.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ops/ngraph_ops.cc
  python/ngraph_bridge/__init__.in.py
  test/ci/buildkite/test_runner.py
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/config_for_grappler_test.cc
  test/graph_rewrites/encapsulate_clusters_test.cc
  test/graph_rewrites/enter_in_catalog_test.cc
  test/graph_rewrites/remove_ngraphassigns.cc
  test/grappler/benchmark_cnn.patch
  test/python/flib_graph_1.pbtxt
  test/python/flib_graph_2.pbtxt
  test/python/tensorflow/tf_unittest_ngraph_with_grappler.patch
  test/python/tensorflow/tf_unittest_runner.py
  test/python/test_updateconfig.py
  tools/test_utils.py
Labels: release candidate

#152 Shrestha/integrate remove ng assign
  ngraph_bridge/enable_variable_ops/ngraph_assign_op.cc
  ngraph_bridge/enable_variable_ops/ngraph_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_catalog.h
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.h
  ngraph_bridge/enable_variable_ops/ngraph_remove_ngraphassigns.cc
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/enable_variable_ops/ngraph_tracked_variable.cc
  ngraph_bridge/ngraph_encapsulate_op.cc
Labels: Ready to merge, release candidate

#146 sarkars/destructor order
  ngraph_bridge/ngraph_encapsulate_op.cc
Labels: release candidate

#159 sarkars/Possible fix for backend settings
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_rewrite_pass.cc
Labels: fully reviewed, release candidate

#149 Sarkars/update tf2ngraph to use rewriterconfig
  test/python/test_rewriter_config_setting.py
  test/python/test_tf2ngraph_functions.py
  test/python/test_tf2ngraph_script.py
  tools/tf2ngraph.py
Labels: release candidate
