Repository tensorflow/ngraph-bridge, pull requests merged in 2019-08, with the labels that each got.

#175 Shrestha/Fix --num_inter_threads
  ngraph_bridge/enable_variable_ops/ngraph_assign_op.cc
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_remove_ngraphassigns.cc
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/enable_variable_ops/ngraph_tracked_variable.cc
  ngraph_bridge/ngraph_encapsulate_op.cc
  test/graph_rewrites/remove_ngraphassigns.cc
Labels: Ready to merge, fully reviewed

#180 sarkars/Upgrade to ngcore24
  CMakeLists.txt
  README.md
  bazel/WORKSPACE
  build_ngtf.py
  ngraph_bridge/version.cc
  python/setup.in.py
Labels: Ready to merge

#183 Sindhu/bfloat16 op tests
  test/python/bfloat16/test_conv2d.py
  test/python/bfloat16/test_conv2dbackpropfilter_nchw.py
  test/python/bfloat16/test_conv2dbackpropfilter_nhwc.py
  test/python/bfloat16/test_conv2dbackpropinput_nchw.py
  test/python/bfloat16/test_conv2dbackpropinput_nhwc.py
  tools/test_utils.py
Labels: Ready to merge, fully reviewed, release candidate

#185 Kanvi/bfloat16 tests
  test/CMakeLists.txt
  test/python/bfloat16/CMakeLists.txt
  test/python/bfloat16/test_fusedbatchnorm_training_nchw.py
  test/python/bfloat16/test_fusedbatchnorm_training_nhwc.py
  test/python/bfloat16/test_maxpoolbackprop_nchw.py
  test/python/bfloat16/test_maxpoolbackprop_nhwc.py
  test/python/test_fusedbatchnorm.py
  test/python/test_l2loss.py
  test/python/test_maxpoolbackprop.py
  test/python/test_relugrad.py
  test/python/test_sparse_softmax_cross_entropy_with_logits.py
Labels: Ready to merge, fully reviewed, release candidate

#188 update ngcore to v0.25.0-rc1
  CMakeLists.txt
  README.md
  bazel/WORKSPACE
  build_ngtf.py
  ngraph_bridge/version.cc
  python/setup.in.py
  test/python/tensorflow/python_tests_list.txt
  test/python/tensorflow/python_tests_list_gpu.txt
  test/python/tensorflow/python_tests_list_mac.txt
Labels: Ready to merge, fully reviewed, release candidate

#179 Vishakha/softplus
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/test_softplus.py
  test/test_nn_ops.cpp
Labels: Ready to merge, fully reviewed

#194 kanvi/yaml file for cpu pipeline for variables path
  test/ci/buildkite/ngtf-cpu_ubuntu-variables.yaml
Labels: wip

#192 Kanvi/unskip py tests
  test/python/test_api.py
  test/python/test_prod.py
  test/python/test_split.py
  test/python/test_squeeze.py
  test/python/test_tanh.py
  test/python/test_while_loop.py
Labels: Ready to merge, fully reviewed

#209 Fixed the memory leak
  ngraph_bridge/ngraph_backend_manager.cc
  ngraph_bridge/ngraph_backend_manager.h
Labels: Ready to merge, fully reviewed

#102 Sindhu/static library
  CMakeLists.txt
  bazel/BUILD
  build_ngtf.py
  examples/cpp/infer_multiple_networks/CMakeLists.txt
  examples/cpp/infer_single/CMakeLists.txt
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/enable_variable_ops/ops/ngraph_ops.cc
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/ngraph_bridge_registry.cc
  ngraph_bridge/ngraph_bridge_registry.h
  ngraph_bridge/ngraph_conversions.cc
  ngraph_bridge/ngraph_conversions.h
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/ops/ngraph_ops.cc
  test/CMakeLists.txt
  test/graph_rewrites/deadness_test.cc
  test/graph_rewrites/disable_ops_test.cc
  test/tf_exec.cpp
  third-party/CMakeLists.txt
  tools/test_utils.py
Labels: fully reviewed, release candidate

#214 sindhu/cmake fix
  test/CMakeLists.txt
Labels: fully reviewed

#139 sindhu/encapsulate_op
  bazel/BUILD
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_encapsulate_op.h
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/CMakeLists.txt
  test/encapsulate_op/encapsulate_op_test.cc
  test/python/test_set_backend.py
Labels: Ready to merge, fully reviewed

#193 Sarkars/ex create tensor 1
  CMakeLists.txt
  README.md
  bazel/BUILD
  bazel/WORKSPACE
  build_ngtf.py
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_pipelined_tensors.cc
  ngraph_bridge/ngraph_pipelined_tensors.h
  ngraph_bridge/version.cc
  python/setup.in.py
  test/CMakeLists.txt
  test/encapsulate_op/encapsulate_op_test.cc
  test/test_index_library.cpp
  test/tf_exec.cpp
Labels: fully reviewed, release candidate

#206 Sarkars/aot 3
  bazel/BUILD
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_encapsulate_clusters.h
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_partial_shapes.cc
  ngraph_bridge/ngraph_partial_shapes.h
  ngraph_bridge/ngraph_rewrite_pass.cc
  test/CMakeLists.txt
  test/graph_rewrites/encapsulate_clusters_test.cc
  test/graph_rewrites/enter_in_catalog_test.cc
  test/graph_rewrites/partial_shapes_test.cc
  test/graph_rewrites/remove_ngraphassigns.cc
  test/python/test_tf2ngraph_functions.py
  test/python/test_tf2ngraph_script.py
  test/python/test_tf2ngraph_shape_hints.py
  tools/run_tf2ngraph_model.py
  tools/sample_optional_params_and_shape_hints.json
  tools/tf2ngraph.py
Labels: release candidate
