Repository tensorflow/ngraph-bridge, pull requests merged in 2019-12, with the labels that each got.

#345 Kanvi/Capture last prefetch
  bazel/BUILD
  ngraph_bridge/enable_variable_ops/ngraph_capture_variables.cc
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/ngraph_capture_variables.cc
  ngraph_bridge/ngraph_find_replace_prefetchdataset.h
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/CMakeLists.txt
  test/test_capture_prefetch.cpp
  test/test_capture_prefetch.pbtxt
  test/test_capture_prefetch_1.pbtxt
  test/test_enter_prefetch_in_catalog.cc
  test/test_utilities.cpp
  test/test_utilities.h
Labels: fully reviewed

#357 sarkars/Fix int32-int64 issue. Removing convert op
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: Ready to merge, fully reviewed

#350 Kanvi/KW issue uninitialized variable in constructor
  experimental/ngraph_device/ngraph_send_recv_ops.cc
  ngraph_bridge/ngraph_encapsulate_op.h
Labels: fully reviewed

#369 Bani / Support tf_ellipsis_mask in stridedslice NGTF-2404
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/tensorflow/python_tests_list.txt
  test/python/tensorflow/python_tests_list_gpu.txt
  test/python/tensorflow/python_tests_list_mac.txt
  test/python/test_slice.py
Labels: release candidate

#353 Vishakh1/round mode br
  ngraph_bridge/ngraph_builder.cc
  test/test_array_ops.cpp
Labels: Ready to merge, release candidate

#370 Sarkars/backend create tensor
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_encapsulate_op.h
  test/tf_exec.cpp
Labels: Ready to merge, fully reviewed, release candidate

#377 Kanvi/Create cc files
  bazel/BUILD
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ngraph_var.cc
  ngraph_bridge/enable_variable_ops/ngraph_var.h
  ngraph_bridge/ngraph_find_replace_prefetchdataset.cc
  ngraph_bridge/ngraph_find_replace_prefetchdataset.h
Labels: Ready to merge, fully reviewed

#375 Kanvi/kw issue
  ngraph_bridge/ngraph_data_cache.h
  ngraph_bridge/ngraph_executor.h
Labels: Ready to merge, fully reviewed

#379 Bani / AddV2 Op NGTF-2426
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/test_math_ops.cpp
Labels: Ready to merge

#385 add install_requires to setup
  python/setup.in.py
Labels: Ready to merge

#372 Kanvi/Transpose PTS
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_executor.cc
  ngraph_bridge/ngraph_pipelined_tensors.cc
  ngraph_bridge/ngraph_pipelined_tensors.h
  test/CMakeLists.txt
  test/python/tensorflow/tf_unittest_ngraph.patch
  test/python/test_variableops_static_input.py
  test/test_capture_prefetch.cpp
  test/test_pipelined_tensor_store.cc
Labels: Ready to merge, fully reviewed

#374 Bani / Support tf_ellipsis_mask in stridedslice NGTF-2404 (#369)
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/tensorflow/python_tests_list.txt
  test/python/tensorflow/python_tests_list_gpu.txt
  test/python/tensorflow/python_tests_list_mac.txt
  test/python/test_slice.py
Labels: Ready to merge

#365 Bani/softmax cross entropy with logits NGTF-2428
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/tensorflow/python_tests_list.txt
  test/python/test_softmax_cross_entropy_with_logits.py
  test/test_nn_ops.cpp
Labels: Ready to merge

#349 MBubula/Added RandomUniformOp
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/model_level_tests/models/MLP/test1/expected.json
  test/model_level_tests/models/MLP/test2/expected.json
  test/python/test_random_uniform.py
Labels: Ready to merge, fully reviewed

#388 Shrestha/var in compute
  bazel/BUILD
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ngraph_assign_op.cc
  ngraph_bridge/enable_variable_ops/ngraph_enter_in_catalog.cc
  ngraph_bridge/enable_variable_ops/ngraph_rewrite_pass.cc
  ngraph_bridge/enable_variable_ops/ngraph_tracked_variable.cc
  ngraph_bridge/enable_variable_ops/ngraph_variable_modifiers.cc
  ngraph_bridge/enable_variable_ops/ngraph_variable_update_ng_tensor_op.cc
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_encapsulate_op_utils.cc
  ngraph_bridge/ngraph_encapsulate_op_utils.h
  ngraph_bridge/ngraph_enter_prefetch_in_catalog.h
  ngraph_bridge/ngraph_executor.cc
  ngraph_bridge/ngraph_prefetch_dataset_op.cc
  ngraph_bridge/ngraph_tensor_manager.cc
  ngraph_bridge/ngraph_tensor_manager.h
  ngraph_bridge/ngraph_tracked_variable.cc
  ngraph_bridge/ngraph_var.cc
  ngraph_bridge/ngraph_var.h
  test/graph_rewrites/test_ng_var_update_ng_tensor.cc
  test/python/test_flib.py
  test/test_ng_var_update_ng_tensor_kernel.cc
  tools/test_utils.py
Labels: fully reviewed

#406 Kanvi/Add missing asserts for python tests
  test/python/test_sigmoid.py
  test/python/test_sign.py
  test/python/test_softmax.py
  test/python/test_stack.py
Labels: Ready to merge, fully reviewed

#395 Bani / Const Op handling for empty and shorter vector values NGTF-2442
  ngraph_bridge/ngraph_utils.h
  test/python/test_const.py
Labels: fully reviewed

#396 Sarkars/Ops cherrypick from r19
  bazel/ngraph.BUILD
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/CMakeLists.txt
  test/python/tensorflow/python_tests_list.txt
  test/python/tensorflow/python_tests_list_gpu.txt
  test/python/tensorflow/python_tests_list_mac.txt
  test/test_array_ops.cpp
  test/test_image_ops.cpp
  test/test_math_ops.cpp
Labels: Ready to merge

#392 sindhu/register backends
  CMakeLists.txt
  bazel/BUILD
  build_ngtf.py
  examples/cpp/inference/CMakeLists.txt
  examples/cpp/inference/infer_multiple_networks.cc
  examples/cpp/inference/infer_single_network.cc
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/ngraph_backend_manager.cc
  test/CMakeLists.txt
  test/graph_rewrites/op_by_op_capability_test.cc
  test/python/test_sign.py
  test/test_ngraph_exec.cpp
Labels: Ready to merge, fully reviewed

#404 Kanvi/fused BMMT support
  ngraph_bridge/ngraph_builder.cc
Labels: Ready to merge, fully reviewed
