Repository tensorflow/ngraph-bridge, pull requests merged in 2019-09, with the labels that each got.

#216 sarkars/Add option in model tester to ignore time checks
  test/model_level_tests/test_main.py
  test/python/test_modeltester.py
Labels: fully reviewed

#181 Vishakha/Fixed RemoveEdege() during the list iteration issue.
  ngraph_bridge/enable_variable_ops/ngraph_replace_op_utilities.cc
  ngraph_bridge/ngraph_capture_variables.cc
  ngraph_bridge/ngraph_rewrite_for_tracking.cc
Labels: fully reviewed

#227 sarkars/Add a comparator to GetReversePostOrder to make toposort deterministic
  ngraph_bridge/ngraph_builder.cc
Labels: fully reviewed

#232 Kanvi/new warnings
  CMakeLists.txt
  bazel/BUILD
  examples/cpp/infer_multiple_networks/inference_engine.cc
  examples/cpp/infer_multiple_networks/inference_engine.h
  examples/cpp/infer_multiple_networks/main.cc
  examples/cpp/tf_label_image_utils.cc
  ngraph_bridge/enable_variable_ops/ngraph_tracked_variable.cc
  ngraph_bridge/enable_variable_ops/ngraph_var.h
  ngraph_bridge/ngraph_assign_clusters.cc
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_cluster_manager.cc
  ngraph_bridge/ngraph_cluster_manager.h
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_tracked_variable.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/tf_deadness_analysis.cc
  test/encapsulate_op/encapsulate_op_test.cc
  test/graph_rewrites/encapsulate_clusters_test.cc
  test/graph_rewrites/enter_in_catalog_test.cc
  test/opexecuter.cpp
  test/test_variable_ops.cpp
Labels: release candidate

#244 sarkars/tf to ng node names
  ngraph_bridge/ngraph_builder.cc
Labels: release candidate

#239 Sarkars/use in graph ngfunc instead of deserializing
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/python/test_ngraph_serialize_flag.py
Labels: fully reviewed, release candidate

#260 Kanvi/bazel build with clang libc++
  CMakeLists.txt
  bazel/WORKSPACE
  bazel/docker/Dockerfile.clang-8.ubuntu18.04
  bazel/docker/README.md
  bazel/ngraph.BUILD
  bazel/tbb.BUILD
  build_ngtf.py
Labels: fully reviewed, release candidate

#255 Sarkars/add provenance tags to all nodes
  README.md
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/version.cc
  python/setup.in.py
  test/ci/buildkite/ngtf-cpu_ubuntu-bin-build.yaml
Labels: fully reviewed, release candidate

#254 Sarkars/modify update config to check if ngoptimizer is enabled
  examples/mnist/mnist_deep_simplified.py
  python/ngraph_bridge/__init__.in.py
  test/python/common.py
  test/python/test_updateconfig.py
Labels: fully reviewed
