Repository tensorflow/ngraph-bridge, pull requests merged in 2019-06, with the labels that each got.

#83 Shrestha/variables_share_buffer_on_cpu
  examples/mnist/mnist_deep_simplified.py
  src/enable_variable_ops/ngraph_assign_op.cc
  src/enable_variable_ops/ngraph_catalog.cc
  src/enable_variable_ops/ngraph_catalog.h
  src/enable_variable_ops/ngraph_tracked_variable.cc
  src/enable_variable_ops/ngraph_var.h
  src/ngraph_encapsulate_op.cc
  src/ngraph_utils.cc
  src/ngraph_utils.h
  test/models/mnist/validate_mnist.sh
Labels: fully reviewed

#96 Shrestha/mnist test
  test/ci/buildkite/ngtf-cpu_centos-grappler.yaml
  test/ci/buildkite/ngtf-cpu_centos.yaml
  test/ci/buildkite/ngtf-cpu_ubuntu.yaml
  test/ci/buildkite/ngtf-cpu_ubuntu_18_04.yaml
  test/ci/buildkite/ngtf-gpu_ubuntu.yaml
  test/python/test_mnist_training.py
Labels: fully reviewed

#105 sarkars/Adding mnist file to build dir
  CMakeLists.txt
  examples/CMakeLists.txt
  tools/test_utils.py
Labels: fully reviewed, release candidate

#92 Avijit/cpp app
  CMakeLists.txt
  examples/cpp/CMakeLists.txt
  examples/cpp/infer_single/CMakeLists.txt
  examples/cpp/infer_single/README.md
  examples/cpp/infer_single/infer_single.cpp
  examples/cpp/label_image_utils.cc
  examples/tf_cpp_examples/Makefile
  examples/tf_cpp_examples/hello_tf.cpp
Labels: release candidate

#99 Sindhu/gathernd
  src/ngraph_builder.cc
  src/ngraph_mark_for_clustering.cc
  test/ci/buildkite/test_runner.py
  test/python/tensorflow/python_tests_list.txt
  test/test_array_ops.cpp
Labels: fully reviewed

#107 Sarkars/build refactor
  build_ngtf.py
  build_tf.py
  maint/apply-code-format.sh
  maint/check-code-format.sh
  test_ngtf.py
  tools/build_utils.py
Labels: fully reviewed, release candidate

#108 Sarkars/update ci pipelines
  test/ci/buildkite/ngtf-cpu_centos-grappler.yaml
  test/ci/buildkite/ngtf-cpu_centos.yaml
  test/ci/buildkite/ngtf-cpu_ubuntu.yaml
  test/ci/buildkite/ngtf-cpu_ubuntu_18_04.yaml
  test/ci/buildkite/ngtf-gpu_ubuntu.yaml
Labels: fully reviewed, release candidate

#88 Kanvi/freshness tracker
  src/enable_variable_ops/ngraph_assign_op.cc
  src/enable_variable_ops/ngraph_capture_variables.cc
  src/enable_variable_ops/ngraph_replace_op_utilities.cc
  src/enable_variable_ops/ngraph_replace_op_utilities.h
  src/enable_variable_ops/ngraph_rewrite_for_tracking.cc
  src/enable_variable_ops/ngraph_tracked_variable.cc
  src/enable_variable_ops/ngraph_variable_modifiers.cc
  src/ngraph_encapsulate_op.cc
  src/ngraph_freshness_tracker.h
  test/python/flib_graph_2.pbtxt
Labels: fully reviewed, release candidate

#109 sarkars/Added fused conv batchnorm relu6 support and test
  src/ngraph_builder.cc
  test/python/test_fusedConv2D.py
Labels: fully reviewed, release candidate

#103 Kanvi/Config_support
  bazel/BUILD
  python/ngraph_bridge/__init__.in.py
  src/CMakeLists.txt
  src/enable_variable_ops/ngraph_rewrite_pass.cc
  src/grappler/ngraph_optimizer.cc
  src/grappler/ngraph_optimizer.h
  src/ngraph_backend_config.cc
  src/ngraph_backend_config.h
  src/ngraph_backend_manager.cc
  src/ngraph_backend_manager.h
  src/ngraph_encapsulate_clusters.cc
  src/ngraph_encapsulate_clusters.h
  src/ngraph_encapsulate_op.cc
  src/ngraph_mark_for_clustering.cc
  src/ngraph_mark_for_clustering.h
  src/ngraph_rewrite_pass.cc
  test/CMakeLists.txt
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/config_for_grappler_test.cc
  test/graph_rewrites/deadness_test.cc
  test/graph_rewrites/disable_ops_test.cc
  test/graph_rewrites/encapsulate_clusters_test.cc
  test/graph_rewrites/mark_for_clustering_test.cc
  test/python/flib_graph_1.pbtxt
  test/python/flib_graph_2.pbtxt
  test/tf_exec.cpp
Labels: fully reviewed, release candidate
