Repository tensorflow/ngraph-bridge, pull requests merged in 2020-01, with the labels that each got.

#397 Kanvi/Make hello_tf bazel example fail in case of no backend
  examples/cpp/hello_tf.cpp
  ngraph_bridge/ngraph_backend_manager.cc
Labels: Ready to merge, fully reviewed

#418 Kanvi/cherry-pick round mode br (#353)
  ngraph_bridge/ngraph_builder.cc
  test/test_array_ops.cpp
Labels: fully reviewed

#419 Kanvi/cherry-pick Fix int32-int64 issue. Removing convert op (#357)
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: fully reviewed

#424 sarkars/Add some utilities to reset the effect of M and A
  ngraph_bridge/ngraph_assign_clusters.cc
  ngraph_bridge/ngraph_assign_clusters.h
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_mark_for_clustering.h
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/graph_rewrites/assign_clusters.cc
  test/graph_rewrites/disable_ops_test.cc
  test/graph_rewrites/mark_for_clustering_test.cc
Labels: fully reviewed

#420 Kanvi/create a dummy backend for testing
  test/CMakeLists.txt
  test/dummy_backend.cpp
  test/dummy_backend.h
  test/test_dummy_backend.cpp
Labels: Ready to merge, fully reviewed

#422 sarkars/Move all maps
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_mark_for_clustering.h
  test/opexecuter.cpp
  test/opexecuter.h
  test/test_math_ops.cpp
Labels: fully reviewed

#425 Kanvi/add missing unref
  ngraph_bridge/ngraph_encapsulate_op_utils.cc
Labels: fully reviewed

#367 Added support for Where Op for NNPI
  ngraph_bridge/ngraph_backend_manager.cc
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: :volcano: Experimental

#441 Jitendra/floordiv fix
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/test_math_ops.cpp
Labels: fully reviewed, release candidate

#451 Peg pip version to 19.3.1
  test/ci/macos/run-ngraph-tf-mac-build.sh
Labels: release candidate

#464 Bani / Update nGraph-Bridge to v0.19.0-rc9 for r0.19 branch
  README.md
  ngraph_bridge/version.cc
  python/setup.in.py
Labels: release candidate

#465 Avoid setting local dict when calling exec() to activate venv
  tools/build_utils.py
Labels: Ready to merge, fully reviewed

#445 Jiminha/gatherndindex
  README.md
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/version.cc
  python/setup.in.py
  test/python/test_gathernd.py
Labels: release candidate

#458 Initial version of nnp CI trigger script
  test/ci/jenkins/jenkins-trigger-nnp.groovy
Labels: Ready to merge

#462 Adds nnpi CI trigger to master
  test/ci/jenkins/jenkins-trigger-nnpi.groovy
Labels: Ready to merge

#468 Kanvi/cherry-pick - Jiminha/gatherndindex (#445)
  ngraph_bridge/ngraph_builder.cc
  test/python/test_gathernd.py
Labels: Ready to merge, bug, fully reviewed

#466 Sarkars/Change the assert to atleast-one-false
  test/test_parallel_executor.cpp
Labels: Ready to merge, bug

#452 Pip version patch
  README.md
  diagnostics/README.md
Labels: Ready to merge, fully reviewed

#472 Copyright 2020 update
  experimental/ngraph_device/ngraph_send_recv_ops.cc
  test/python/test_fusedMatMul.py
  test/python/test_gathernd.py
Labels: Ready to merge

#470 ashahba/Fix 'ngtf-cpu-model-test' check
  test/model_level_tests/models/benchmarks/test1_resnet/expected.json
  test/model_level_tests/models/benchmarks/test2_densenet/expected.json
  test/model_level_tests/models/benchmarks/test3_mobilenet/expected.json
  test/model_level_tests/models/benchmarks/test4_inceptionv4/expected.json
  test/model_level_tests/models/nmt/test1/expected.json
  test/model_level_tests/models/tfmodels/test1_resnet20_nhwc/expected.json
  test/model_level_tests/models/tfmodels/test2_resnet20_nchw/expected.json
Labels: Ready to merge

#399 Sindhu/bfloat16 support
  bazel/BUILD
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/enable_variable_ops/ngraph_variable_modifiers.cc
  ngraph_bridge/ngraph_register_stub_kernels.cc
  ngraph_bridge/ngraph_register_stub_kernels.h
  ngraph_bridge/ngraph_utils.cc
  test/python/test_bfloat16.py
Labels: Ready to merge
