Repository tensorflow/ngraph-bridge, pull requests merged in 2020-08, with the labels that each got.

#602 Add tests for TransposeSinking pass
  test/CMakeLists.txt
  test/pass/transpose_sinking_test.cpp
  test/test_utilities.h
Labels: wip

#623 Avoid using ngraph::replace_node_update_name
  ngraph_bridge/ie_executable.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/test_array_ops.cpp
Labels: bug

#625 fix const to param conversion
  ngraph_bridge/ie_executable.cc
Labels: bug

#627 Fix path of downloaded pretrained model when running CI RN50 job
  tools/test_utils.py
Labels: Ready to merge, fully reviewed

#632 Remove quantization ops from IE tests and clustering
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/cpp_tests_list_IECPU.txt
Labels: Ready to merge

#633 Grouped Sum Op-Tests into sets using GTest Fixture
  test/cpp_tests_list_IECPU.txt
  test/test_math_ops.cpp
Labels: Ready to merge, fully reviewed

#639 Upgrade depthwiseconv2d translation
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_conversions.h
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/test_depthwiseconv2d.py
Labels: Ready to merge, fully reviewed
