Repository tensorflow/ngraph-bridge, pull requests merged in 2020-12, with the labels that each got.

#716 Fix commit id for tf-ov model zoo
  test/models/tf_ov_model_zoo/run_infer_single.sh
Labels: bug, comp:build

#710 Use canonical TF convention for encapsulate op/kernel
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  ngraph_bridge/ngraph_encapsulate_impl.cc
  ngraph_bridge/ngraph_encapsulate_impl.h
  ngraph_bridge/ngraph_register_stub_kernels.cc
  ngraph_bridge/ngraph_register_stub_kernels.h
  ngraph_bridge/ops/ngraph_encapsulate_op.cc
  test/CMakeLists.txt
  test/encapsulate_op/encapsulate_op_test.cc
Labels: comp:core, refactoring

#712 Remove unused parameters from nGraph function
  ngraph_bridge/executable.cc
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  test/python/tensorflow/tests_linux_cpu.txt
  test/python/test_variableops_static_input.py
  test/python/tests_linux_cpu.txt
  test/tests_linux_cpu.txt
Labels: bug, comp:core

#718 Inaccurate output with transpose sinking for graphs with multi-outputs nodes
  test/opexecuter.cpp
  test/opexecuter.h
  test/pass/transpose_sinking_test.cpp
  test/tests_linux_cpu.txt
Labels: bug, comp:core

#719 fix model testing CI issue
  test/models/tf_ov_model_zoo/run_infer_multiple.sh
Labels: bug, comp:ci

#720 Remove unused TransposeFolding pass
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/pass/transpose_folding.cc
  ngraph_bridge/pass/transpose_folding.h
Labels: comp:core

#722 Support for TF gather op
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/test_gather.py
  test/python/tests_common.txt
  test/python/tests_linux_cpu.txt
  test/test_array_ops.cpp
Labels: comp:core

#715 Upgrade OV to pre-release 2021.2
  build_ngtf.py
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  test/python/tensorflow/tests_common.txt
  test/test_ngraph_exec.cpp
Labels: comp:build, comp:core, enhancement

#721 Update pack/unpack translations
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: comp:core, enhancement

#717 Enable dumping of IE plugin graphs
  ngraph_bridge/executable.cc
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  ngraph_bridge/pass/transpose_sinking.cc
Labels: enhancement

#730 Enable shape information for nGraph graphs
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
Labels: enhancement

#731 Upgrade to opset5
  ngraph_bridge/backend.cc
  ngraph_bridge/default_opset.h
  ngraph_bridge/executable.cc
  ngraph_bridge/ngraph_builder.cc
Labels: comp:core

#733 Update DepthwiseConv2DNative translation to use GroupConvolution
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: comp:core

#737 Use unsqueeze for ExpandDims op translation
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
Labels: comp:core

#739 Remove executable caching in backend
  ngraph_bridge/backend.cc
  ngraph_bridge/backend.h
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_backend_manager.cc
  test/test_ngraph_exec.cpp
Labels: comp:core, refactoring

#738 Clean up unused methods in utils
  ngraph_bridge/executable.cc
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_assign_clusters.cc
  ngraph_bridge/ngraph_assign_clusters.h
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_cluster_manager.h
  ngraph_bridge/ngraph_deassign_clusters.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  ngraph_bridge/ngraph_mark_for_clustering.h
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/ngraph_utils.cc
  ngraph_bridge/ngraph_utils.h
  ngraph_bridge/pass/transpose_sinking.cc
  test/graph_rewrites/assign_clusters.cc
  test/graph_rewrites/disable_ops_test.cc
  test/graph_rewrites/mark_for_clustering_test.cc
  test/test_ngraph_exec.cpp
  test/test_utilities.h
Labels: comp:core, refactoring

#735 Add translation for Where op
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/test_select.py
  test/python/tests_linux_cpu.txt
  test/python/tests_linux_gpu.txt
Labels: comp:core, enhancement

#740 Add NMSV2 translation
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/tensorflow/tests_common.txt
  test/python/tensorflow/tests_linux_cpu.txt
  test/python/tensorflow/tests_linux_gpu.txt
  test/python/test_nms.py
  test/python/tests_linux_cpu.txt
  test/python/tests_linux_gpu.txt
Labels: comp:core

#696 Add use_openvino_from_location option
  CMakeLists.txt
  build_ngtf.py
  build_ov.py
  ngraph_bridge/CMakeLists.txt
  tools/build_utils.py
Labels: comp:build, refactoring

#753 Add manifest/workdir options to CI models script
  test/ci/buildkite/models-cpu.yml
  test/models/tf_ov_model_zoo/run_infer_multiple.sh
Labels: comp:ci

#749 Handle skipped inputs correctly in the executable
  ngraph_bridge/executable.cc
  ngraph_bridge/executable.h
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_assign_clusters.cc
Labels: bug, comp:core

#752 Fix multi-output handling bug in TS
  ngraph_bridge/pass/transpose_sinking.cc
  test/models/tf_ov_model_zoo/models_cpu.txt
  test/models/tf_ov_model_zoo/models_gpu.txt
  test/models/tf_ov_model_zoo/models_myriad.txt
  test/pass/transpose_sinking_test.cpp
  test/tests_linux_cpu.txt
  test/tests_linux_gpu.txt
Labels: bug, comp:core

#758 Use env var to set min non-trivial nodes
  ngraph_bridge/ngraph_deassign_clusters.cc
Labels: enhancement

#727 Range op translation
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_mark_for_clustering.cc
  test/python/tensorflow/tests_linux_cpu.txt
  test/python/tensorflow/tests_linux_gpu.txt
  test/python/tests_linux_gpu.txt
  test/test_math_ops.cpp
Labels: comp:core, enhancement

#769 Update Readme
  README.md
Labels: comp:docs
