Repository tensorflow/ngraph-bridge, pull requests merged in 2021-01, with the labels that each got.

#771 Upgrade to TF2.3
  CMakeLists.txt
  build_ngtf.py
  examples/cpp/infer_multiple_networks.cc
  examples/cpp/infer_single_network.cc
  logging/tf_graph_writer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_encapsulate_clusters.cc
  python/setup.in.py
  test/ci/buildkite/cpu.yml
  test/ci/buildkite/models-cpu.yml
  test/ci/buildkite/run_pipeline.sh
  test/graph_rewrites/deadness_test.cc
  test/opexecuter.h
  test/pass/transpose_sinking_test.cpp
  test/python/tensorflow/tf_unittest_ngraph.patch
  test/python/tensorflow/tf_unittest_ngraph_with_grappler.patch
  test/test_array_ops.cpp
  test/test_math_ops.cpp
  test/test_ngraph_exec.cpp
  test/test_nn_ops.cpp
  test/tf_exec.cpp
Labels: comp:core, future change

#775 Fix nGraph bridge version printed at the end of build
  python/ngraph_bridge/__init__.in.py
Labels: bug

#779 Enable py tests for VPU pipeline
  test/python/tests_linux_myriad.txt
Labels: comp:ci

#782 Enable TF python tests for VPU
  test/python/tensorflow/tests_common.txt
  test/python/tensorflow/tests_linux_myriad.txt
Labels: comp:ci

#783 build - make cxx_abi=0 default
  build_ngtf.py
  build_ov.py
  build_tf.py
  cmake/external_gtest.cmake
  tools/build_utils.py
Labels: comp:build

#786 Remove ngraph_logger lib
  CMakeLists.txt
  logging/CMakeLists.txt
  logging/ngraph_log.cc
  logging/tf_graph_writer.cc
  logging/tf_graph_writer.h
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/assign_clusters.cc
  ngraph_bridge/backend_manager.cc
  ngraph_bridge/deassign_clusters.cc
  ngraph_bridge/encapsulate_clusters.cc
  ngraph_bridge/executable.cc
  ngraph_bridge/grappler/ngraph_add_identityn.cc
  ngraph_bridge/grappler/ngraph_add_identityn.h
  ngraph_bridge/grappler/ngraph_optimizer.cc
  ngraph_bridge/grappler/ngraph_optimizer.h
  ngraph_bridge/kernels/ngraph_encapsulate_op.cc
  ngraph_bridge/log.h
  ngraph_bridge/ngraph_builder.cc
  ngraph_bridge/ngraph_conversions.h
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/pass/transpose_sinking.cc
  ngraph_bridge/utils.cc
  ngraph_bridge/utils.h
  test/graph_rewrites/assign_clusters.cc
  test/graph_rewrites/backend_manager_test.cc
  test/graph_rewrites/config_for_grappler_test.cc
  test/graph_rewrites/deadness_test.cc
  test/graph_rewrites/mark_for_clustering_test.cc
  test/graph_rewrites/op_by_op_capability_test.cc
  test/opexecuter.cpp
  test/pass/transpose_sinking_test.cpp
  test/test_array_ops.cpp
  test/test_math_ops.cpp
  test/test_nn_ops.cpp
  test/test_utilities.cpp
Labels: comp:core, refactoring

#788 Allow building against custom TF version
  tools/build_utils.py
Labels: comp:build, enhancement

#789 Enable plots for bench-cpu pipeline
  test/ci/buildkite/bench-cpu.yml
  test/models/tf_ov_model_zoo/gen_plot.py
  test/models/tf_ov_model_zoo/run_infer_multiple.sh
  test/models/tf_ov_model_zoo/run_infer_single.sh
Labels: comp:ci

#791 Add benchmarking pipelines for GPU and MYRIAD
  test/ci/buildkite/run_pipeline.sh
Labels: comp:ci, plugin:gpu, plugin:vpu

#787 Unify grappler optimizer and rewrite-pass
  ngraph_bridge/CMakeLists.txt
  ngraph_bridge/grappler/ngraph_add_identityn.cc
  ngraph_bridge/ngraph_optimizer.cc
  ngraph_bridge/ngraph_optimizer.h
  ngraph_bridge/ngraph_rewrite_pass.cc
  ngraph_bridge/ngraph_rewrite_pass.h
Labels: comp:core, refactoring

#790 Upgrade to TF 2.4.1
  build_ngtf.py
  python/setup.in.py
  test/ci/buildkite/bench-cpu.yml
  test/ci/buildkite/cpu.yml
  test/ci/buildkite/models-cpu.yml
  test/ci/buildkite/run_pipeline.sh
  test/python/tensorflow/tests_linux_cpu.txt
  test/python/tensorflow/tests_linux_gpu.txt
  test/python/tensorflow/tests_linux_myriad.txt
  tools/test_utils.py
Labels: comp:build

#792 Decrease iterations for models-* pipelines
  test/models/tf_ov_model_zoo/run_infer_single.sh
Labels: comp:ci

#796 Use OV 2021.2 distribution for benchmarking pipelines
  test/ci/buildkite/bench-cpu.yml
  test/models/tf_ov_model_zoo/run_infer_single.sh
Labels: comp:ci
